_target_: hgattn.opts.SingSpeedOpts

defaults:
  - _self_
  - models@arch: simple
  - data@data: melody
  - optim@optim: adam
  - sched@sched: reduce_on_plateau

report_every: 100
schedule_every: 50
warmup_steps: 1000
num_epochs: 100
do_compile: true 
do_test_metrics: true
max_melodies_to_use: 100000000

