_target_: hgattn.opts.TempoInvariantOpts

defaults:
  - _self_
  - models@arch: simple
  - data@data: melody
  - optim@optim: adam
  - sched@sched: reduce_on_plateau

report_every: 100
num_epochs: 100
do_compile: true 

