_target_: hgattn.opts.TestDatasetOpts

defaults:
  - _self_
  - data: expr2

is_train: true
dataset_size: 100000
num_epochs: 1
batch_size: 10
seed: null
do_mapreduce: false
do_print_raw: false 
do_print: false 
do_speedtest: false
do_validate: false

hydra:
  run:
    dir: ${oc.env:HOME}/.hydra
  output_subdir: .hydra



