_target_: hgattn.opts.RunOpts

defaults:
  - _self_ 
  - arch: gen_size1
  - attn: graph_rope
  - data: expr1
  - optim: adam
  - sched: slow 
  - embed: std
  - logger: streamvis
  - train: max
  - metric: m10
  - debug: d1

seed: ${random_int:}
init_scale: 1.0


hydra:
  run:
    # Falls back to "." (current working directory) if HYDRA_LOGGING is not set
    dir: ${oc.env:HYDRA_LOGGING,.}/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

