_target_: hgattn.opts.RunOpts

defaults:
  - _self_ 
  - arch: gen_size1
  - attn: rope
  - data: coff3
  - optim: adam_slow
  - sched: slow 
  - embed: std
  - logger: text
  - train: small
  - metric: m10
  - debug: d1

seed: ${random_int:}
code_tweak: none
data_desc: none

hydra:
  run:
    dir: ${oc.env:HOME}/.hydra
  output_subdir: .hydra

