_target_: hgattn.opts.TrainOpts

do_compile: true
do_test_metrics: false 
report_every: 100
num_epochs: 100000
batch_size: 64
start_ds_fraction: 0.01
epoch_ds_increment: 0.001

use_label_mask: false



