apiVersion: batch/v1
kind: Job
metadata:
  name: cache-wheels
  namespace: strange-loop
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 30
  template:
    spec:
      restartPolicy: Never
      imagePullSecrets:
        - name: strange-loop-snapshots-robot
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "astera.org/namespace"
          operator: "Exists"
          effect: "NoSchedule"
      volumes:
        - name: home-storage
          persistentVolumeClaim:
            claimName: hrbigelow-home
      containers:
        - name: compile
          image: harbor.astera.sh/strange-loop/cuda:13.3.1-devel-ubuntu26.04-custom
          workingDir: /workspace/code
          restartPolicy: Never

          resources:
            limits:
              nvidia.com/gpu: "1"

          volumeMounts:
            - name: home-storage
              mountPath: /workspace

          env:
            - name: UV_PROJECT_ENVIRONMENT
              value: "/opt/venv"
            - name: UV_COMPILE_BYTECODE
              value: "1"
            - name: VIRTUAL_ENV
              value: "/opt/venv"
            - name: UV_CACHE_DIR
              value: "/workspace/.cache/uv"
            - name: UV_LINK_MODE
              value: "copy"
            # - name: UV_PYTHON_INSTALL_DIR
              # value: "/opt/uv-python"

          command: ["/bin/bash", "-c"]
          args:
            - |
              set -euo pipefail

              trap 'echo "Command Failed at line $LINENO. Sleeping 2 hours"; sleep 7200' ERR

              cd strange-loop
              uv sync --extra cu133

              cd ../att3ntion
              uv build --wheel --no-build-isolation-package att3ntion . --out-dir /workspace/wheels

              cd ../streamvis/client
              uv build --wheel . --out-dir /workspace/wheels

              trap - ERR
              echo "Built wheels for att3ntion and streamvis"

