_target_: hgattn.opts.SimpleCompOpts

num_tokens: 0    # fill from data
model_dim: 128 
mlp_hidden_dim: 512
num_heads: 8
n_layers: 4 
attn_impl: hypergraph-tiled # hypergraph-tiled, hypergraph-naive, graph
pos_embed_type: none
n_recurse: 5




